import Head from 'next/head';
import { useState } from 'react';
import About from '../components/About';
import Main from '../components/Main';
import Navbar from '../components/Navbar';
import Skills from '../components/Skills';

export default function Home() {
	const baseImagePath = '/assets/skills';
	const [skills, setSkills] = useState([
		/* Multiple of 4 for styling */
		{ name: 'HTML', src: `${baseImagePath}/html-logo.png` },
		{ name: 'CSS', src: `${baseImagePath}/css-logo.png` },
		{ name: 'Javascript', src: `${baseImagePath}/js-logo.png` },
		{ name: 'Node.js', src: `${baseImagePath}/node-logo.png` },
		{ name: 'Express', src: `${baseImagePath}/express-logo.png` },
		{ name: 'React', src: `${baseImagePath}/react-logo.png` },
		{ name: 'Next.js', src: `${baseImagePath}/next-logo.png` },
		{ name: 'MongoDB', src: `${baseImagePath}/mongo-logo.png` },
	]);

	return (
		<div>
			<Head>
				<title>Eli | Fullstack Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Main />
			<About />
			<Skills skills={skills} />
		</div>
	);
}
